# The name of the workflow
name: SonarCloud

# Defines when the action should run
on:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main
  # Also triggers the workflow on pull request events
  pull_request:
    types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "build"
  build:
    # The name of the job
    name: Build and analyze
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # A sequence of tasks that will be executed as part of the job
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      # Sets up a JDK 17 environment for the job with the 'zulu' distribution
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available
      # Caches SonarCloud packages to speed up workflow execution
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      # Caches Gradle packages to speed up workflow execution
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      # Grants execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./demo/gradlew          
      # Builds and analyzes the code
      - name: Build and analyze
        env:
          # Needed to get PR information, if any. This token is auto created/managed by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          # SonarCloud token for authentication
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Specifies that the working directory for the following step is './demo'
        working-directory: ./demo
        # Runs the command for building and analyzing the code, skipping tests
        run: ./gradlew build sonar --info -x test